# Generated by Django 4.2.6 on 2023-11-08 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="guid",
            field=models.UUIDField(
                auto_created=True, db_index=True, default=uuid.uuid4, unique=True
            ),
        ),
    ]
