# Generated by Django 4.2.6 on 2023-11-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                ("content", models.TextField()),
                ("coin", models.PositiveIntegerField(default=0)),
                (
                    "complexity",
                    models.TextField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                            ("Difficult", "Difficult"),
                        ],
                        default="Easy",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Questions",
                "db_table": "millionaire_questions",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("total", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InProgress", "In Progress"),
                            ("Closed", "Closed"),
                            ("Done", "Done"),
                        ],
                        default="InProgress",
                        max_length=12,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        max_length=5,
                        related_name="questions",
                        to="millionaire.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table": "millionaire_quizzes",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                ("body", models.TextField()),
                ("correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="millionaire.question",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Question Options",
                "db_table": "millionaire_question_options",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="millionaire.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="millionaire.quiz",
                    ),
                ),
                (
                    "selected",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected",
                        to="millionaire.option",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quiz Answers",
                "db_table": "millionaire_quiz_answers",
                "ordering": ["pk"],
                "unique_together": {("quiz", "question")},
            },
        ),
    ]
