# Generated by Django 4.2.2 on 2023-06-23 22:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        editable=False,
                        help_text="The unique identifier of the board.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                (
                    "grid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(blank=True, null=True),
                            blank=True,
                            null=True,
                            size=None,
                        ),
                        blank=True,
                        default=list,
                        help_text="The grid of the board.",
                        null=True,
                        size=None,
                        verbose_name="Grid",
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        choices=[(8, "Eight"), (10, "Ten")],
                        default=8,
                        help_text="The length of the board.",
                        verbose_name="Length",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the board was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the board was updated.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_ended",
                    models.BooleanField(
                        default=False,
                        help_text="The status of the game.",
                        verbose_name="Is ended",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The owner of the board.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        help_text="The players of the board.",
                        related_name="boards_players",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Players",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        blank=True,
                        help_text="The queue of the board.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boards_queue",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Queue",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The winner of the board.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boards_winner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Winner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkers board",
                "verbose_name_plural": "Checkers boards",
                "db_table": "checkers_boards",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="Histories",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        editable=False,
                        help_text="The unique identifier of the history.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                (
                    "from_point",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        help_text="The from point of the history.",
                        size=2,
                        verbose_name="From point",
                    ),
                ),
                (
                    "to_point",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        help_text="The to point of the history.",
                        size=2,
                        verbose_name="To point",
                    ),
                ),
                (
                    "taken_points",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(), size=2
                        ),
                        blank=True,
                        help_text="The taken points of the history.",
                        null=True,
                        size=None,
                        verbose_name="Taken points",
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the history was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        help_text="The board of the history.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="checkers.board",
                        verbose_name="Board",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="The player of the history.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkers history",
                "verbose_name_plural": "Checkers histories",
                "db_table": "checkers_histories",
                "ordering": ["-pk"],
            },
        ),
    ]
