# Generated by Django 4.2.2 on 2023-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="The status of the board.",
                verbose_name="Is active",
            ),
        ),
    ]
