# Generated by Django 4.2.2 on 2023-10-27 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkers", "0002_board_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="players",
        ),
        migrations.AlterField(
            model_name="board",
            name="guid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="The unique identifier of the board.",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="GUID",
            ),
        ),
        migrations.CreateModel(
            name="BoardPlayers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stone_type",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "White"), (3, "Black")], default=2
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="checkers.board"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("board", "stone_type")},
            },
        ),
    ]
