# Generated by Django 4.2.6 on 2023-11-07 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("checkers", "0004_board_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="histories",
            name="from_point",
        ),
        migrations.RemoveField(
            model_name="histories",
            name="to_point",
        ),
        migrations.AddField(
            model_name="histories",
            name="grid_changes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), size=2
                ),
                help_text="Move points of the history.",
                null=True,
                size=None,
                verbose_name="Grid changes",
            ),
        ),
        migrations.AlterField(
            model_name="histories",
            name="guid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="The unique identifier of the history.",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="GUID",
            ),
        ),
    ]
