# Generated by Django 4.2.2 on 2023-10-29 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("checkers", "0004_board_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="histories",
            name="guid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="The unique identifier of the history.",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="GUID",
            ),
        ),
    ]
