# Generated by Django 4.2.6 on 2023-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkers", "0005_remove_histories_from_point_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiplayerGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.CharField(max_length=100)),
                ("recipient_id", models.CharField(max_length=100)),
                ("board_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
