# Generated by Django 4.2.6 on 2023-10-30 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkers", "0005_alter_histories_guid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="histories",
            name="to_point",
        ),
        migrations.AddField(
            model_name="histories",
            name="to_points",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), size=2
                ),
                blank=True,
                help_text="To points of the history.",
                null=True,
                size=None,
                verbose_name="To point",
            ),
        ),
    ]
