"""
Django's settings for server project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from typing import Any, List, Dict
from pydantic import Field
from pydantic_settings import BaseSettings

from .database import DatabaseSettings


# import environ

# env = environ.Env()
# environ.Env.read_env('.env')  # reading .env file


class DjangoSettings(BaseSettings):
    """
        Django settings class
    """

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG: bool = Field(True, env='DEBUG')

    ALLOWED_HOSTS: List[str] = Field(["*"], env='ALLOWED_HOSTS')

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR: Path = Path(__file__).resolve().parent.parent

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY: str = 'django-insecure-0yzvn5l@@**01)$b#rw8e^3srgo7r#q#s%sv-_)0ia2x9zju#y'

    # Application definition
    INSTALLED_APPS: List[str] = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',

        # Third party apps
        "django_filters",
        "strawberry.django",

        # Local apps
        'account',
        'jwtberry.blackberry',
        'core',
        'games',
        'games.checkers',
    ]

    AUTH_USER_MODEL: str = 'account.User'

    MIDDLEWARE: List[str] = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF: str = 'server.urls'

    TEMPLATES: List[Dict] = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION: str = 'server.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/4.0/ref/settings/#databases
    DATABASES: DatabaseSettings = DatabaseSettings()

    # Password validation
    # https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS: List[Dict] = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/4.0/topics/i18n/

    LANGUAGE_CODE: str = 'en-us'

    TIME_ZONE: str = 'UTC'

    USE_I18N: bool = True

    USE_TZ: bool = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/4.0/howto/static-files/

    STATIC_URL: str = 'static/'

    # Default primary key field type
    # https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD: str = 'django.db.models.BigAutoField'

    # Add JSONWebTokenBackend backend to your AUTHENTICATION_BACKENDS:
    AUTHENTICATION_BACKENDS: List[str] = [
        "jwtberry.backends.JwtAuthBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

    class Config:
        env_prefix = 'APP_'
        case_sensitive = True
