# Generated by Django 4.2.6 on 2023-11-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bazarblot", "0002_alter_table_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundplayerscards",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players_cards",
                to="bazarblot.round",
            ),
        ),
    ]
