# Generated by Django 4.2.6 on 2023-12-29 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="guid",
            field=models.UUIDField(
                auto_created=True, db_index=True, default=uuid.uuid4, unique=True
            ),
        ),
    ]
